branch-defaults:
  master:
    environment: SlideStreamServerDev
    group_suffix: null
global:
  application_name: SlideStreamServer
  branch: null
  default_ec2_keyname: SlideEBKey
  default_platform: Node.js
  default_region: us-east-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
